### ISSUE TITLE
gcov_to_es not working

### ISSUE THREAD

**Issue by klahnakoski** [marco-c/grcov#10]
Please update the install script to install grcov so that the ActiveData-ETL can use it.  ETL machines are setup by machine, there will be no human to fill in the blanks for scripts that almost work.

**Comment by marco-c** [comment]
The script downloads grcov in a directory of your choice, you just need to make sure that this directory is in the PATH.

**Comment by marco-c** [comment]
You can use the new script like this: `./install.sh /usr/local/bin`.
