### ISSUE TITLE
Add integration test with a gcno zip and a gcda zip

### ISSUE THREAD

**Issue by marco-c** [marco-c/grcov#116]

**Comment by svensevenslow** [comment]
Hi! I'd like to work on this. Could you please elaborate a bit on what is to be done. The test needs to be written in https://github.com/marco-c/grcov/blob/master/src/producer.rs ?

**Comment by marco-c** [comment]
We need to modify https://github.com/marco-c/grcov/blob/master/tests/test.rs to also test the case where we give grcov as input the ZIP files instead of a directory.

**Comment by marco-c** [comment]
So you can add a new test that does something like this:
```
            println!("\nLLVM");
            let llvm_version = get_version("llvm-config", "--version");
            make(path, "clang++");
            run(path);
            check_equal_ade(&read_expected(path, "llvm", &llvm_version, "ade"), &run_grcov(path, true, "ade"));
            check_equal_coveralls(&read_expected(path, "llvm", &llvm_version, "coveralls"), &run_grcov(path, true, "coveralls"), skip_branches);
do_clean(path);
```

with the tests/basic/ test, and modifying run_grcov to choose if it has to run grcov on the directory or after zipping the files in the directory.

**Comment by calixteman** [comment]
I'm taking this bug since we need to have quickly some tests to be able to release a new version.
