### ISSUE TITLE
Is uncovered lines outside functions legitimate?

### ISSUE THREAD

**Issue by klahnakoski** [marco-c/grcov#14]
This query
    {
	"from":"coverage",
	"where":{"eq":{"_id":"tc.601123:60111463.55"}}
    }
https://activedata.allizom.org/tools/query.html#query_id=w+8Nmnkj

Showing source for `/home/worker/workspace/build/src/js/src/vm/AsyncFunction.cpp`

Shows a orphan record with some lines uncovered:

	"method":{
		"total_covered":0,
		"covered":[],
		"total_uncovered":7,
		"uncovered":[223,210,227,216,220,232,230],
		"percentage_covered":0
	}

Is that possible?   Sorry for the dumb question.

**Comment by marco-c** [comment]
This could be because of https://github.com/klahnakoski/ActiveData-ETL/issues/25; at the moment if a function is not executed it is skipped by grcov and the uncovered lines will go in orphan.
