### ISSUE TITLE
What should the percentage be when we have 0 covered and 0 uncovered lines

### ISSUE THREAD

**Issue by marco-c** [marco-c/grcov#16]

**Comment by klahnakoski** [comment]
None, or Null, or even better, do not include the `percentage` property

**Comment by klahnakoski** [comment]
There are functions/sources with zero lines?!!

**Comment by klahnakoski** [comment]
In general, the following are equivalent:
* `null`
* empty array `[]`
* property is missing

For the sake of size and clarity; neglect the property, when storing `null` or empty arrays `[]`

**Comment by marco-c** [comment]
> There are functions/sources with zero lines?!!

Compiler optimizations can do strange things 😄
