### ISSUE TITLE
Get grcov working on Mozilla's "build" type one-click loaners

### ISSUE THREAD

**Issue by mjzffr** [marco-c/grcov#20]
For more context, see https://bugzilla.mozilla.org/show_bug.cgi?id=1350446

I'd like to run grcov on a one-click loaner. The default version of gcc on the loaner is incompatible with grcov. There is no easy way to install a newer version. 
* We could ask to reconfigure the one-click-loaner environment to match what is actually used for the build.
* Can grcov support earlier versions of gcc?

The default version of gcc available on a one-click loaner from a linux build job (e.g. [1]) is 4.4.7. This is not what is used by the actual build task that generated gcno files (./mach build), which actually uses tooltool to fetch gcc 4.9.4. [2,3]

I can modify the PATH on the loaner to use gcc 4.9.4, but I'm still missing libraries to get grcov working. 
```
./grcov: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./grcov)
./grcov: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./grcov)
```

[1] https://treeherder.mozilla.org/#/jobs?repo=try&author=mjzffr@gmail.com&selectedJob=92502848
[2] https://treeherder.mozilla.org/logviewer.html#?job_id=92502848&repo=try&lineNumber=1095
[3] https://treeherder.mozilla.org/logviewer.html#?job_id=92502848&repo=try&lineNumber=1005

**Comment by marco-c** [comment]
For the GLIBC issue, there are two options:
1) compile and distribute grcov as a standalone binary (using musl instead of glibc);
2) compile grcov on one of the loaner machines, so that the binary links to the libc version that's available on those machines.

It should definitely be possible to support older versions of gcc.

**Comment by marco-c** [comment]
Could you try this binary (with the PATH modified to use gcc 4.9.4):
[grcov.zip](https://github.com/marco-c/grcov/files/949169/grcov.zip)

**Comment by mjzffr** [comment]
The provided grcov binary runs.

I also tried running `code-coverage.py` and it yields a report successfully: https://github.com/mjzffr/ccov-reports/tree/master/grcov-one-click-240417-f170ebfc2dfd/report

FYI: when using `--no-download` on the one-click loaner I get an empty output.info on the one-click loaner (although this works fine locally when I place the same gcda/gcno zip files in ccov-artifacts). 

```
python firefox-code-coverage/code-coverage.py workspace/build/src $MH_BRANCH $GECKO_HEAD_REV --grcov ./grcov --no-download
Running grcov... 0
Reading data file /home/worker/output.info
genhtml: ERROR: no valid records found in tracefile /home/worker/output.info
Traceback (most recent call last):
  File "firefox-code-coverage/code-coverage.py", line 147, in <module>
    main()
  File "firefox-code-coverage/code-coverage.py", line 143, in main
    generate_report(os.path.abspath(args.src_dir))
  File "firefox-code-coverage/code-coverage.py", line 111, in generate_report
    raise Exception("Error while running genhtml.")
Exception: Error while running genhtml.
(grcov) [root@6ad4646442bd ~]# cat output.info 
TN:
```

**Comment by marco-c** [comment]
> I also tried running code-coverage.py and it yields a report successfully: https://github.com/mjzffr/ccov-reports/tree/master/grcov-one-click-240417-f170ebfc2dfd/report

Awesome, so from now on, whenever I release a new grcov version I can simply provide a standalone binary on https://github.com/marco-c/grcov/releases/latest.

> FYI: when using --no-download on the one-click loaner I get an empty output.info on the one-click loaner (although this works fine locally when I place the same gcda/gcno zip files in ccov-artifacts).

Is the `ccov-artifacts` directory you manually created in your working dir?
Here's the code that lists the artifacts:
https://github.com/marco-c/firefox-code-coverage/blob/master/code-coverage.py#L81

**Comment by marco-c** [comment]
> Is the ccov-artifacts directory you manually created in your working dir?
Here's the code that lists the artifacts:
https://github.com/marco-c/firefox-code-coverage/blob/master/code-coverage.py#L81

Perhaps it would be better to modify the parameter `--no-download` into `--with-artifacts=PATH_TO_ARTIFACTS` to avoid issues.

**Comment by mjzffr** [comment]
Yes, it was in my working dir. 

Changing to --with-artifacts is a good idea, either way.

**Comment by marco-c** [comment]
I opened #22 to support GCC < 4.9.0 (even though at this point it isn't strictly required, as we can just set the PATH to use GCC 4.9.4) and https://github.com/marco-c/firefox-code-coverage/issues/4 to support --with-artifacts instead of --no-download (but on a one-click-loaner I guess it's easier for users to just let the script download the artifacts).
