### ISSUE TITLE
Support outputting branch coverage information in LCOV format

### ISSUE THREAD

**Issue by marco-c** [marco-c/grcov#39]
Currently we support outputting it in the Coveralls format, we should support the LCOV format too.

**Comment by Sush0512** [comment]
Dear @marco-c ,
I would like to work on the issue. I understand the issue and have gone through the resources mentioned. In `README` it is mentioned that we can output the code coverage information in `lcov`.   Please, can you guide me through the necessary things to be done.

Thank you,
Sushma

**Comment by marco-c** [comment]
Hello @Sush0512. The `output_lcov` function in src/output.rs needs to be modified to support outputting branch information too (the format is described in my earlier comment).

**Comment by marco-c** [comment]
`output_coveralls` for example is outputting the branch information for the `coveralls` format.

**Comment by Sush0512** [comment]
Thank you for the information. I started working on the issue and want to clarify the following.

-  should the `block number` be 0 as in coveralls?
-  `branch hit count` is the number of times the `taken` value is non zero?

**Comment by marco-c** [comment]
> should the block number be 0 as in coveralls?

Yes.

> branch hit count is the number of times the taken value is non zero?

Yes, if by "branch hit count" you mean the "BRH" value.
