### ISSUE TITLE
Requires gcov?

### ISSUE THREAD

**Issue by klahnakoski** [marco-c/grcov#5]
Does this require gcov?  Please add an example script that can setup some Linux to run the tests.

    let status = Command::new("gcov") 

https://github.com/marco-c/grcov/blob/master/src/main.rs#L101

**Comment by marco-c** [comment]
Yes, it uses `gcov` to parse `gcno` and `gcda` files.

**Comment by marco-c** [comment]
On Linux, at least on Ubuntu, `gcov` is bundled with `gcc`, so you just need to install `gcc` (at least version 4.9, which is the same minimum requirement for a Firefox build).
