### ISSUE TITLE
grcov panics when using LLVM flag

### ISSUE THREAD

**Issue by lght** [marco-c/grcov#51]
Platform: Linux x86-64
Compiler: Clang 5, GCC 7.2.0

This issue may be due to me misunderstanding how to use `grcov`.

After generating `.gcda` / `.gcno` files with `cargo-cov`, `grcov` panics when trying to generate `coveralls` formatted files with:

```
grcov /dir/with/gcda-gcno-files --llvm -t coveralls --token *** --commit-sha *** > out.info
```

Here is an example of the errors:
```
'Failed parsing execution count: function _ZN5alloc5slice8{{impl}}18into_vec<[u8; 20]>E called 0 returned 0% blocks executed 0%: ParseIntError { kind: InvalidDigit }'
```

Not sure if this is related to #25. Thanks in advance for any help.

**Comment by marco-c** [comment]
Which version of grcov are you testing?
There might be a bug in the master branch that I haven't had time to debug yet.

Could you also upload here the gcda/gcno files in a ZIP?

**Comment by marco-c** [comment]
>  There might be a bug in the master branch that I haven't had time to debug yet.

Sorry, I meant 0.1.29. Could you test 0.1.28?

**Comment by lght** [comment]
I am using 0.1.29, will try out 0.1.28.

**Comment by lght** [comment]
Here are the gcda/gcno files, with a text file of the generated error: [grcov-llvm-panic.zip](https://github.com/marco-c/grcov/files/1573650/grcov-llvm-panic.zip)

**Comment by marco-c** [comment]
@lght the archive is empty :)

**Comment by lght** [comment]
derp, here is a second attempt: 
[grcov-llvm-panic.zip](https://github.com/marco-c/grcov/files/1577445/grcov-llvm-panic.zip)

**Comment by marco-c** [comment]
The gcno files in the archive seem to be invalid, as they can't be parsed with `llvm-cov`. Maybe try uploading them on another service and then put the link here?

**Comment by marco-c** [comment]
Anyway, I've managed to reproduce the error, so I don't need them anymore. Thanks for the report!

**Comment by marco-c** [comment]
I think there's an underlying issue with the mangling of the symbol. I can implement a workaround in grcov, but we should fix this in Rust.

**Comment by lght** [comment]
Ok, is the fix in Rust something in how `cargo-cov` is mangling? Brand new to the tooling, but happy to help if I can.

**Comment by marco-c** [comment]
Could you test again with current master?

**Comment by lght** [comment]
Tested again with master, and your latest commit fixed the panic. Thank you much :)
