### ISSUE TITLE
Automatically detect GCC version during tests

### ISSUE THREAD

**Issue by sylvestre** [marco-c/grcov#64]
> running 1 test
> rm -f a.out a.exe main.gcno main.gcda default.profraw
> g++ -fprofile-arcs -ftest-coverage main.c
> 12345689test test_integration ... FAILED
> 
> failures:
> 
> ---- test_integration stdout ----
> 	
> 
> tests/switch
> GCC
> thread 'test_integration' panicked at 'COMPILER_VER env variable is not defined: NotPresent', /checkout/src/libcore/result.rs:906:4
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> 
> 
> failures:
>     test_integration
> 
> test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
> 
> error: test failed, to rerun pass '--test test'
>

**Comment by marco-c** [comment]
You need to set the `COMPILER_VER` environment variable to your version of gcc.
I should add this to the docs (or detect it automatically).

**Comment by sylvestre** [comment]
I think you can detect it without too many issues! :)
