### ISSUE TITLE
Add a deploy script

### ISSUE THREAD

**Issue by klahnakoski** [marco-c/grcov#7]
It would be nice to have ActiveData-ETL use this.  We need a deploy script (Ubuntu) to help test it, and to know all the know all the dependencies.

**Comment by klahnakoski** [comment]
Looks like the .travis script is good enough

**Comment by marco-c** [comment]
```Bash
#!/bin/bash

PLATFORM=linux-x86_64
VERSION=v0.1.1

sudo apt-get install gcc
rm -f grcov grcov-$PLATFORM.tar.bz2
wget https://github.com/marco-c/grcov/releases/download/$VERSION/grcov-$PLATFORM.tar.bz2
tar xf grcov-$PLATFORM.tar.bz2
rm grcov-$PLATFORM.tar.bz2
```

Would this be enough? We don't need to download and install Rust and compile `grcov`, we can just use the released build.

**Comment by klahnakoski** [comment]
Yes, that looks good.

**Comment by marco-c** [comment]
Cool. I will also add the script to this repo.
