### ISSUE TITLE
Intermittent thread '<unnamed>' panicked at 'gcov wasn't successfully executed on /tmp/grcov.o62FwPBSpb5p/media/gmp-clearkey/0.1/Unified_cpp_gmp-clearkey_0.10_1.gcno', src/main.rs:672:8

### ISSUE THREAD

**Issue by cpearce** [marco-c/grcov#74]
One of the Mozilla sheriffs filed a bug in bugzilla.mozilla.org due to grcov crashing while running "Linux x64 CCov opt Mochitests with e10s test-linux64-ccov/opt-mochitest-media-e10s-1 M-e10s(mda1)", log:
https://treeherder.mozilla.org/logviewer.html#?job_id=158959011&repo=mozilla-central&lineNumber=22921

Excerpt:

[task 2018-01-28T20:57:58.951Z] 20:57:58     INFO - Reading from file tmpfile_stderr
[task 2018-01-28T20:57:58.952Z] 20:57:58    ERROR -  thread '<unnamed>' panicked at 'gcov wasn't successfully executed on /tmp/grcov.o62FwPBSpb5p/media/gmp-clearkey/0.1/Unified_cpp_gmp-clearkey_0.10_1.gcno', src/main.rs:672:8
[task 2018-01-28T20:57:58.952Z] 20:57:58    ERROR -  note: Run with `RUST_BACKTRACE=1` for a backtrace.
[task 2018-01-28T20:57:58.952Z] 20:57:58    ERROR -  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', /checkout/src/libcore/result.rs:906:4
[task 2018-01-28T20:57:58.953Z] 20:57:58    ERROR - Exception during post-action for run-tests: Traceback (most recent call last):
[task 2018-01-28T20:57:58.954Z] 20:57:58    ERROR -   File "/builds/worker/workspace/mozharness/mozharness/base/script.py", line 2010, in run_action
[task 2018-01-28T20:57:58.954Z] 20:57:58    ERROR -     method(action, success=success and self.return_code == 0)
[task 2018-01-28T20:57:58.954Z] 20:57:58    ERROR -   File "/builds/worker/workspace/mozharness/mozharness/mozilla/testing/codecoverage.py", line 193, in _package_coverage_data
[task 2018-01-28T20:57:58.954Z] 20:57:58    ERROR -     throw_exception=True,
[task 2018-01-28T20:57:58.955Z] 20:57:58    ERROR -   File "/builds/worker/workspace/mozharness/mozharness/base/script.py", line 1595, in get_output_from_command
[task 2018-01-28T20:57:58.955Z] 20:57:58    ERROR -     raise subprocess.CalledProcessError(p.returncode, command)
[task 2018-01-28T20:57:58.955Z] 20:57:58    ERROR - CalledProcessError: Command '['/tmp/tmpFJWzBD/grcov', '-t', 'lcov', '-p', '/builds/worker/workspace/build/src/', '--ignore-dir', 'gcc', '/tmp/tmpFJWzBD/target.code-coverage-gcno.zip', '/builds/worker/workspace/code-coverage-gcda.zip']' returned non-zero exit status 101
[task 2018-01-28T20:57:58.955Z] 20:57:58     INFO - Running post-action listener: _resource_record_post_action
[task 2018-01-28T20:57:58.956Z] 20:57:58     INFO - [mozharness: 2018-01-28 20:57:58.956015Z] Finished run-tests step (success)
[task 2018-01-28T20:57:58.956Z] 20:57:58    FATAL - Aborting due to failure in post-action listener.
[task 2018-01-28T20:57:58.956Z] 20:57:58    FATAL - Running post_fatal callback...
[task 2018-01-28T20:57:58.956Z] 20:57:58    FATAL - Exiting -1

The bug is:
https://bugzilla.mozilla.org/show_bug.cgi?id=1433868

**Comment by marco-c** [comment]
Thanks for letting me know. It looks like `gcov` failed to run, it's the first time it happens.
I'll investigate.

**Comment by marco-c** [comment]
I think it's a version mismatch between the GCC used to compile and the gcov used to parse the gcda files.
