### ISSUE TITLE
Print errors to stderr

### ISSUE THREAD

**Issue by marco-c** [marco-c/grcov#75]

**Comment by vsham20** [comment]
Hi @marco-c , I want to pick-up this issue, Can you please provide more details. Thanks

**Comment by marco-c** [comment]
Currently we are printing errors to stdout (with println!), we should instead print them to stderr (with eprintln!).

**Comment by vsham20** [comment]
Great,and which version of Rust is used here?

**Comment by marco-c** [comment]
The project should be buildable with the latest stable and nightly versions of Rust.
