### ISSUE TITLE
Windows deploy script?

### ISSUE THREAD

**Issue by klahnakoski** [marco-c/grcov#8]
Using grcov prevents debugging the ETL pipeline on my local windows machine.

**Comment by marco-c** [comment]
I'm going to build a Windows build and add it to the releases, so something similar to the script from #7 could be used in this case too.

**Comment by marco-c** [comment]
Added Windows build to https://github.com/marco-c/grcov/releases/tag/v0.1.2.
From now on, I will always provide both a Linux build and a Windows build for every new release.
